#!/bin/bash
# CANONICAL SOURCE — managed by runcycles/.github/shared-config/
# Do not edit this file in individual repos. Changes should be made here
# and synced to all repos via scripts/sync-claude-config.sh.
#
# Session start hook: ensure global Claude Code deny rules and git proxy config.
#
# This script runs at session start and does TWO things:
#
#   1. (Per-user, idempotent) Writes MCP deny rules to ~/.claude/settings.json
#      so mcp__github__ file-mutation tools are blocked globally — even in
#      cross-repo sessions where deny rules in a single repo wouldn't apply.
#
#   2. (MULTI-REPO MUTATION) If a local git proxy is detected in any sibling
#      repo under /home/user/*, rewrites the `origin` remote URL of EVERY
#      sibling github.com repo under /home/user/ to route through the proxy.
#      This is intentional for Claude Code remote-environment workflows where
#      multiple Cycles repos are cloned side-by-side and all need the same
#      proxy. It is surprising if you only know about the per-repo .claude/
#      hook, so it is called out explicitly here.
#
# OPT-OUT: set CYCLES_CLAUDE_SKIP_REMOTE_REWRITE=1 to disable Part 2 entirely
# (useful for local Claude Code runs where you do not want sibling repos
# touched). Part 1 always runs.
#
# Issue: runcycles/.github#63

set -e

# --- Part 1: Global MCP deny rules ---

GLOBAL_SETTINGS="$HOME/.claude/settings.json"

if ! [ -f "$GLOBAL_SETTINGS" ] || ! grep -q "mcp__github__push_files" "$GLOBAL_SETTINGS" 2>/dev/null; then
  mkdir -p "$HOME/.claude"

  if [ -f "$GLOBAL_SETTINGS" ]; then
    TMP_SETTINGS=$(mktemp)
    if command -v python3 &>/dev/null; then
      python3 -c "
import json
with open('$GLOBAL_SETTINGS') as f:
    settings = json.load(f)
perms = settings.setdefault('permissions', {})
deny = perms.get('deny', [])
needed = [
    'mcp__github__create_or_update_file',
    'mcp__github__push_files',
    'mcp__github__delete_file'
]
for rule in needed:
    if rule not in deny:
        deny.append(rule)
perms['deny'] = deny
with open('$TMP_SETTINGS', 'w') as f:
    json.dump(settings, f, indent=2)
    f.write('\n')
" && mv "$TMP_SETTINGS" "$GLOBAL_SETTINGS"
    else
      rm -f "$TMP_SETTINGS"
    fi
  else
    cat > "$GLOBAL_SETTINGS" << 'EOF'
{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  "permissions": {
    "deny": [
      "mcp__github__create_or_update_file",
      "mcp__github__push_files",
      "mcp__github__delete_file"
    ]
  }
}
EOF
  fi
fi

# --- Part 2: Fix git remote URLs to use local proxy (MULTI-REPO) ---
# Some sessions clone repos via github.com directly, which lacks push credentials.
# If the local git proxy is running, rewrite remote URLs to use it.
#
# WARNING: this part iterates every directory under /home/user/ and mutates the
# `origin` remote of any github.com repo it finds, not just the current
# checkout. See the file-level header for the rationale and opt-out.

if [ "${CYCLES_CLAUDE_SKIP_REMOTE_REWRITE:-}" = "1" ]; then
  # Opt-out path for local Claude Code runs that should not touch sibling repos.
  exit 0
fi

# Detect local git proxy: look for the proxy in any sibling repo's remote URL
PROXY_BASE=""
for dir in /home/user/*/; do
  if [ -d "$dir/.git" ]; then
    url=$(git -C "$dir" remote get-url origin 2>/dev/null || true)
    if echo "$url" | grep -q 'local_proxy.*127.0.0.1'; then
      # Extract base URL: http://local_proxy@127.0.0.1:PORT/git
      PROXY_BASE=$(echo "$url" | sed 's|\(http://local_proxy@127\.0\.0\.1:[0-9]*/git\)/.*|\1|')
      break
    fi
  fi
done

if [ -n "$PROXY_BASE" ]; then
  # Fix any repos with github.com remote URLs
  for dir in /home/user/*/; do
    if [ -d "$dir/.git" ]; then
      url=$(git -C "$dir" remote get-url origin 2>/dev/null || true)
      # Match github.com URLs (SSH or HTTPS) and rewrite to local proxy
      if echo "$url" | grep -qE '(git@github\.com:|https?://github\.com/)'; then
        # Extract org/repo from the URL
        repo_path=$(echo "$url" | sed -E 's|.*github\.com[:/](.*)\.git$|\1|; s|.*github\.com[:/](.*)$|\1|')
        if [ -n "$repo_path" ]; then
          new_url="${PROXY_BASE}/${repo_path}"
          git -C "$dir" remote set-url origin "$new_url" 2>/dev/null || true
        fi
      fi
    fi
  done
fi
